# Generated by Django 6.0.7 on 2026-09-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor', '0006_donation_pickup_date_donation_pickup_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('DONATION_SUBMITTED', 'Donation submitted'), ('DONATION_APPROVED', 'Donation approved'), ('DONATION_REJECTED', 'Donation rejected'), ('DONATION_COLLECTED', 'Donation collected'), ('DONATION_MATCHED', 'Donation matched'), ('REQUEST_MATCHED', 'Requirement matched'), ('RESOURCE_ALLOCATED', 'Resource allocated'), ('PICKUP_CREATED', 'Pickup created'), ('PICKUP_CONFIRMED', 'Pickup confirmed'), ('PICKUP_DISPATCHED', 'Pickup dispatched'), ('DONATION_DELIVERED', 'Donation delivered'), ('PICKUP_CANCELLED', 'Pickup cancelled')], max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_key', models.CharField(blank=True, max_length=255, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donor.donor')),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='donor.ngo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['donor', 'is_read', '-created_at'], name='notif_donor_read_created_idx'), models.Index(fields=['ngo', 'is_read', '-created_at'], name='notif_ngo_read_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('donor__isnull', False), ('ngo__isnull', True)), models.Q(('donor__isnull', True), ('ngo__isnull', False)), _connector='OR'), name='notification_exactly_one_recipient'), models.UniqueConstraint(condition=models.Q(('donor__isnull', False), ('event_key__isnull', False)), fields=('donor', 'event_key'), name='notification_donor_event_key_uniq'), models.UniqueConstraint(condition=models.Q(('event_key__isnull', False), ('ngo__isnull', False)), fields=('ngo', 'event_key'), name='notification_ngo_event_key_uniq')],
            },
        ),
    ]
