# Generated by Django 6.0.7 on 2026-08-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_pickuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_status',
            field=models.CharField(blank=True, choices=[('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Accepted', 'Accepted'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Not Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='pickup_status',
            field=models.CharField(blank=True, choices=[('Not Scheduled', 'Not Scheduled'), ('Scheduled', 'Scheduled'), ('Accepted', 'Accepted'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Not Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='donationallocation',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
