"""
Django settings for donation_system project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY

SECRET_KEY = 'django-insecure-^kjz#n_w5r5fxxrez!@n@htjxlz1$oq#00&fh73b-91et!ph-+'

DEBUG = True

ALLOWED_HOSTS = []



INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Django REST Framework
    'rest_framework',

    # JWT
    'rest_framework_simplejwt',

    # CORS
    'corsheaders',

    # Our App
    'donor',
    'notifications.apps.NotificationsConfig',
]


MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'donation_system.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'donation_system' / 'templates'
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'donation_system.wsgi.application'



# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ai_donation',
        'USER': 'postgres',
        'PASSWORD': 'ai_donation01',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files

STATIC_URL = 'static/'



# Media files

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



# REST Framework + JWT Authentication

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'donor.authentication.CustomJWTAuthentication',

    ),

}



# JWT Token Settings (optional)

from datetime import timedelta


SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

}
# JWT Token Settings

from datetime import timedelta

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

}


# REST Framework + JWT Authentication

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'donor.authentication.CustomJWTAuthentication',

    ),

}


# ---------------- CORS SETTINGS ----------------

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
