# Generated by Django 6.0.7 on 2026-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Books', 'Books'), ('Medicine', 'Medicine'), ('Electronics', 'Electronics'), ('Other', 'Other')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
