# Generated by Django 6.0.7 on 2026-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Donor', 'Donor'), ('NGO', 'NGO')], max_length=20),
        ),
    ]
